language: node_js
node_js:
 - "0.10"

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - npm install
 - ./node_modules/.bin/bower install
 - ./node_modules/.bin/grunt

after_script:
 - ./node_modules/.bin/grunt coveralls
